- name: "Install Nginix"
  hosts: localhost
  connection: local
  tasks:
    - name: "To check Nginix installed or not"
      shell: "rpm -qa |grep -i nginix|wc -l"
      register: x

    - name: "Install Nginix"
      dnf:
        name: nginix
        state: installed
        when: x.stdout != 0

    - name: "Start Nginix service"
      service:
        name: nginix
        state: installed
