- name: "Install tomcat"
  hosts: 172.31.91.246
  connection: local
  become: true
  tasks:

    - name: "Install tomcat"
      dnf:
       name: "tomcat"
       state: installed



       #"dnf module install tomcat:1.24 -y"

   # - name: "update yum"
   #   dnf:
   #     name: "*"
   #     state: latest


      #dnf:
       # name: nginix
       # state: installed
        #when: x.stdout != 0

    #- name: "Start Nginix service"
    #  service:
    #    name: nginix
    #    state: started
